#!/usr/bin/env python3
"""Re-vendor the LCMA web assets from the annotation-ui repo into this fork.

Two build artifacts from the annotation-ui project are vendored into TiLiA:

    dist-embed/embed.html      ->  tilia/ui/timelines/lcma/builder/embed.html
    src/generated/vocab.json   ->  tilia/ui/timelines/lcma/vocab.json

``embed.html`` is the single-file QWebEngine builder; ``vocab.json`` gives ``span_view`` the
ontology abbreviations. Both are generated, so they drift whenever the annotation-ui ontology
or builder changes. Keeping them in the repo (rather than building at install time) keeps the
desktop build self-contained, but it has to be refreshed by hand — this script is that hand.

Next to the assets it writes ``builder/SOURCE.txt`` — the annotation-ui commit the bundle was
built from and whether that source tree was dirty — so a vendored file is traceable to a source
revision and an unclean (non-reproducible) vendor is visible in the diff.

Usage::

    python scripts/sync_lcma_assets.py [--source PATH] [--build] [--check]

    --source PATH   annotation-ui repo (default: $LCMA_ANNOTATION_UI or ../lcma-annotation-ui)
    --build         run `npm run build:embed` and `npm run ontology:gen` in the source first
    --check         do not copy; exit 1 if any vendored file differs (a CI / pre-commit gate),
                    and report the provenance recorded in builder/SOURCE.txt
"""

from __future__ import annotations

import argparse
import filecmp
import os
import shutil
import subprocess
import sys
from pathlib import Path

FORK_ROOT = Path(__file__).resolve().parent.parent

# (path of the artifact within the annotation-ui repo, destination within this fork)
ASSETS = [
    ("dist-embed/embed.html", FORK_ROOT / "tilia/ui/timelines/lcma/builder/embed.html"),
    ("src/generated/vocab.json", FORK_ROOT / "tilia/ui/timelines/lcma/vocab.json"),
]

# Provenance manifest written next to the assets: which annotation-ui commit they came from.
PROVENANCE_FILE = FORK_ROOT / "tilia/ui/timelines/lcma/builder/SOURCE.txt"

# Commands that (re)generate the artifacts above, run in the annotation-ui repo with --build.
BUILD_COMMANDS = [
    ["npm", "run", "build:embed"],  # -> dist-embed/embed.html
    ["npm", "run", "ontology:gen"],  # -> src/generated/vocab.json
]


def resolve_source(arg: str | None) -> Path:
    raw = (
        arg
        or os.environ.get("LCMA_ANNOTATION_UI")
        or str(FORK_ROOT.parent / "lcma-annotation-ui")
    )
    src = Path(raw).expanduser().resolve()
    if not src.is_dir():
        sys.exit(
            f"annotation-ui source not found: {src}\n"
            "pass --source PATH or set LCMA_ANNOTATION_UI"
        )
    return src


def run_build(source: Path) -> None:
    for cmd in BUILD_COMMANDS:
        print(f"$ ({source}) {' '.join(cmd)}")
        subprocess.run(cmd, cwd=source, check=True)


def _git(source: Path, *args: str) -> str | None:
    try:
        return subprocess.run(
            ["git", "-C", str(source), *args],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError, OSError):
        return None


def source_provenance(source: Path) -> dict[str, str]:
    """Describe the annotation-ui revision the vendored assets were built from."""
    commit = _git(source, "rev-parse", "HEAD")
    if commit is None:
        return {"commit": "unknown", "branch": "", "dirty": "unknown"}
    branch = _git(source, "rev-parse", "--abbrev-ref", "HEAD") or ""
    if branch == "HEAD":  # detached checkout (e.g. vendoring from a pinned worktree)
        branch = "(detached)"
    dirty = bool(_git(source, "status", "--porcelain"))
    return {"commit": commit, "branch": branch, "dirty": "true" if dirty else "false"}


def write_provenance(prov: dict[str, str], dest: Path = PROVENANCE_FILE) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(
        "# Provenance of the vendored LCMA assets in this directory.\n"
        "# Generated by scripts/sync_lcma_assets.py -- do not edit by hand.\n"
        "source_repo: lcma-annotation-ui\n"
        f"commit: {prov['commit']}\n"
        f"branch: {prov['branch']}\n"
        f"dirty: {prov['dirty']}\n",
        encoding="utf-8",
    )


def read_provenance(src: Path = PROVENANCE_FILE) -> dict[str, str]:
    prov: dict[str, str] = {}
    if src.is_file():
        for line in src.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and ":" in line:
                key, _, value = line.partition(":")
                prov[key.strip()] = value.strip()
    return prov


def _report_provenance(current: dict[str, str]) -> None:
    recorded = read_provenance()
    if not recorded:
        print("[provenance] SOURCE.txt missing — vendored assets have no recorded origin")
        return
    print(
        f"[provenance] vendored from commit {recorded.get('commit', '?')[:9]} "
        f"(dirty={recorded.get('dirty', '?')}); source now at {current['commit'][:9]}"
    )
    if recorded.get("dirty") == "true":
        print(
            "warning: recorded provenance is 'dirty' — the committed bundle was vendored from "
            "an unclean source tree and may not be reproducible.",
            file=sys.stderr,
        )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--source", help="path to the annotation-ui repo")
    ap.add_argument(
        "--build",
        action="store_true",
        help="rebuild the artifacts in the source repo first",
    )
    ap.add_argument(
        "--check",
        action="store_true",
        help="do not copy; exit 1 if any vendored file is stale",
    )
    args = ap.parse_args()

    source = resolve_source(args.source)
    if args.build:
        run_build(source)

    prov = source_provenance(source)
    if prov["dirty"] == "true" and not args.check:
        print(
            f"warning: annotation-ui at {source} has uncommitted changes; the vendored bundle "
            f"will not be reproducible from commit {prov['commit'][:9]} alone. Commit the "
            "source first for a clean provenance stamp.",
            file=sys.stderr,
        )

    missing = [rel for rel, _ in ASSETS if not (source / rel).is_file()]
    if missing:
        hint = "" if args.build else " (run with --build, or build the source first)"
        sys.exit(f"source artifact(s) missing: {', '.join(missing)}{hint}")

    stale = []
    for rel, dest in ASSETS:
        src_file = source / rel
        same = dest.is_file() and filecmp.cmp(src_file, dest, shallow=False)
        rel_dest = dest.relative_to(FORK_ROOT)
        if args.check:
            print(f"[{'ok' if same else 'STALE'}] {rel_dest}  <-  {rel}")
            if not same:
                stale.append(rel)
        elif same:
            print(f"[unchanged] {rel_dest}")
        else:
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(src_file, dest)
            print(f"[vendored]  {rel_dest}  <-  {rel}")

    if args.check:
        _report_provenance(prov)
    else:
        write_provenance(prov)
        flag = "dirty" if prov["dirty"] == "true" else "clean"
        print(
            f"[provenance] {PROVENANCE_FILE.relative_to(FORK_ROOT)}  ->  "
            f"commit {prov['commit'][:9]} ({flag})"
        )

    if args.check and stale:
        print(
            f"\n{len(stale)} vendored asset(s) are stale. Run:\n"
            "  python scripts/sync_lcma_assets.py --build\n"
            "and commit the result.",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
